### ISSUE TITLE
KeyError: 'SLURM_PROCID'

### ISSUE THREAD

**Issue by xinxin12345** [ModelTC/mqbench-paper#1]
请问这个是什么原因呢，单机多卡可以使用slurm吗？

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "mqbench/prototype/solver/cls_quant_solver.py", line 393, in <module>
    main()
  File "mqbench/prototype/utils/dist.py", line 44, in wrapper
    dist_init()
  File "mqbench/prototype/utils/dist.py", line 53, in dist_init
    proc_id = int(os.environ['SLURM_PROCID'])
  File "/opt/conda/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'SLURM_PROCID'

**Comment by ChuyuWang949** [comment]
同样的问题请问解决了吗
